version: '3.8'

services:
  openvino-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvino-server
    restart: always
    network_mode: host
    devices:
      - /dev/dri:/dev/dri

  qdrant:
    image: qdrant/qdrant:latest
    container_name: mnemosyne-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /opt/qdrant_storage:/qdrant/storage
